//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServer.ServiceReferenceHall {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceHall.IServiceHall")]
    public interface IServiceHall {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHall/VisualizzazioneSale", ReplyAction="http://tempuri.org/IServiceHall/VisualizzazioneSaleResponse")]
        string VisualizzazioneSale();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHall/VisualizzazioneSale", ReplyAction="http://tempuri.org/IServiceHall/VisualizzazioneSaleResponse")]
        System.Threading.Tasks.Task<string> VisualizzazioneSaleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHall/RappresentaSale", ReplyAction="http://tempuri.org/IServiceHall/RappresentaSaleResponse")]
        string RappresentaSale(int codice_evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHall/RappresentaSale", ReplyAction="http://tempuri.org/IServiceHall/RappresentaSaleResponse")]
        System.Threading.Tasks.Task<string> RappresentaSaleAsync(int codice_evento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceHallChannel : WCFServer.ServiceReferenceHall.IServiceHall, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHallClient : System.ServiceModel.ClientBase<WCFServer.ServiceReferenceHall.IServiceHall>, WCFServer.ServiceReferenceHall.IServiceHall {
        
        public ServiceHallClient() {
        }
        
        public ServiceHallClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHallClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHallClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHallClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string VisualizzazioneSale() {
            return base.Channel.VisualizzazioneSale();
        }
        
        public System.Threading.Tasks.Task<string> VisualizzazioneSaleAsync() {
            return base.Channel.VisualizzazioneSaleAsync();
        }
        
        public string RappresentaSale(int codice_evento) {
            return base.Channel.RappresentaSale(codice_evento);
        }
        
        public System.Threading.Tasks.Task<string> RappresentaSaleAsync(int codice_evento) {
            return base.Channel.RappresentaSaleAsync(codice_evento);
        }
    }
}
